name: Build

on:
  push:
    branches: [ "main" ]

permissions: 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker meta
      id: meta_build
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/deb4sh/docker-jekyll
        tags: |
          type=sha
